accounts/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required, user_passes_test


def login_forbidden(function=None):
    actual_decorator = user_passes_test(
        lambda u: u.is_anonymous,
    )
    if function:
        return actual_decorator(function)
    return actual_decorator

urlpatterns = [
    path('login', views.login, name='login'),
    path('register', views.register, name="register"),
    path('dashboard', views.dashboard, name="dashboard"),
    path('admin_dashboard', views.admin_dashboard, name="admin_dashboard"),
    path('logout', views.logout, name="logout"),

    # Password Reset and Change URL's
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(
         template_name='accounts/password_change_done.html'),
         name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(
         template_name='accounts/password_change.html'),
         name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(
         template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='accounts/password_reset_confirm.html'),
        name='password_reset_confirm'),

    path('password_reset/', login_forbidden(auth_views.PasswordResetView.as_view(
        template_name='accounts/password_reset_confirm.html')),
        name='password_reset'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='accounts/password_reset_complete.html'),
        name='password_reset_complete'),
]

froggyco/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('pages.urls')),
    path('superuser/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('accounts/', include('accounts.urls')),
    path('orders/', include('orders.urls')),
]

pages/urls.py
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('about', views.about, name="about"),
    path('promos', views.promos, name="promos"),
    path('talent', views.talent, name="talent"),
    path('interaction', views.interaction, name="interaction"),
    path('404', views.page_404, name="404"),
]

projects/urls.py
from django.urls import path,include
from . import views
    
app_name = 'projects'

urlpatterns = [
    path('',views.projects, name="projects"),
    path('<slug>',views.project_detail, name="project_detail"),
    path('<slug>/checkout',views.checkout, name="checkout"),
    path('<slug>/watch',views.watch, name="watch")
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.models import User

class UserUpdateForm(forms.ModelForm):
    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['first_name','last_name','email']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.views import PasswordResetView
from .forms import UserUpdateForm
from orders.models import Order
from django.db.models import Sum, Count, Max
from django.http import JsonResponse, HttpResponse
from django.core import serializers
# from django.utils.timezone import datetime 
from datetime import datetime



# Create your views here
def register(request):
    #if user is authenticated already and try to use login url, this will redirect to another page
    if request.user.is_authenticated :
        return redirect('dashboard')

    #user registration
    if request.method == 'POST':
        #Get form values
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']

        #check if password match
        if password == password2:
            #checks username
            if User.objects.filter(username=username).exists():
                messages.error(request, 'Username is taken, Please try different username')
                return redirect('register')
            else:
                #checks email
                if User.objects.filter(email=email).exists():
                    messages.error(request, 'This email already exists, Please use  different email')
                    return redirect('register')
                else:
                    #looks good
                    # user registered as a new user, now user can log in...
                    user = User.objects.create_user(
                        username=username,
                        password=password,
                        email=email,
                        first_name=first_name,
                        last_name=last_name
                    )

                    #login after registered // if you want user to automatically login
                    # // after registered, use this code below,

                    # auth.login(request, user)
                    # messages.success(request, 'Welcome ! You are now logged in')
                    # return redirect('index')

                    #redirect to login page after registered // if you want user to manually login
                    # // after registered, use this code below,

                    user.save();
                    messages.success(request, 'You are now registered and can log in')
                    return redirect('login')
        else:
            messages.error(request, 'passwords do not match')
            return redirect('register')
    else:
        return render(request, 'accounts/register.html')


def login(request):

    #if user is authenticated already and try to use login url, this will redirect to another page
    if request.user.is_authenticated :
        return redirect('dashboard')

    #login authentication

    if request.method == 'POST':
        #login user
        username = request.POST['username']
        password = request.POST['password']
        
        user = auth.authenticate(username = username, password = password)

        if user is not None:
            auth.login(request, user)
            messages.success(request, 'You are now logged in')
            return redirect('dashboard')
        else:
            messages.error(request, 'Invalid username or password')
            return redirect('login')
    else:
        return render(request, 'accounts/login.html')


@login_required
def logout(request):
    if request.method == 'POST':
        auth.logout(request)
        # messages.success(request, 'You are now logged out')
        return render(request,'accounts/logout.html')   

@login_required
def dashboard(request):

    user_orders = Order.objects.order_by('order_date').filter(user_id=request.user.id)

    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)

        if u_form.is_valid():
            u_form.save()
            messages.success(request, 'Your account has been updated!')
            return redirect('dashboard')
    else:
        u_form = UserUpdateForm(instance=request.user)

    videos_count = Order.objects.filter(user_id=request.user.id).count()
    money_spent = Order.objects.filter(user_id=request.user.id).aggregate(Sum('price'))

    print(money_spent)

    context = {
        'u_form':u_form,
        'orders':user_orders,
        'videos_count':videos_count,
        'money_spent':money_spent,
    }
    
    return render(request, 'accounts/dashboard.html', context)
    
@login_required
@user_passes_test(lambda u: u.is_superuser)
def admin_dashboard(request):
    orders = Order.objects.order_by('-order_date')
    total_revenue = Order.objects.all().aggregate(Sum('price'))
    total_orders = Order.objects.count()
    counts = Order.objects.values("project_id","project_title","price","project_category").annotate(Count("project_id")).order_by('-price')[:5]
    theatre_revenue = Order.objects.filter(project_category="THEATRE").aggregate(Sum('price'))
    theatre_orders = Order.objects.filter(project_category="THEATRE").count()
    movie_revenue = Order.objects.filter(project_category="MOVIE").aggregate(Sum('price'))
    movie_orders = Order.objects.filter(project_category="MOVIE").count()
    today_date = datetime.now()
    today = Order.objects.filter(order_date__date=datetime.date(today_date)).values('order_date__date').order_by('-order_date__date').annotate(sum=Sum('price')).annotate(Count("project_id"))
    daily = Order.objects.filter().values('order_date__date').order_by('-order_date__date').annotate(sum=Sum('price')).annotate(Count("project_id"))
    videos = Order.objects.values("project_id","project_title","price","project_category").annotate(Count("project_id")).order_by('-price')
    users = User.objects.all()

    print(today)

    context = {
        'orders':orders,
        'revenue':total_revenue,
        'total_orders':total_orders,
        'counts':counts,
        'theatre_revenue':theatre_revenue,
        'theatre_orders':theatre_orders,
        'movie_revenue':movie_revenue,
        'movie_orders':movie_orders,
        'today':today,
        'daily':daily,
        'videos':videos,
        'users':users,
    }

    return render(request, 'accounts/admin_dashboard_1.html',context)

pages/templates/accounts/admin_dashboard.html
{% extends 'layout.html' %}
{% block content %}
{% load static %}
{% include 'partials/_navbar.html' %}
{% include 'partials/_datatables.html' %}
{% load mathfilters %}
<section class="admin_dashboard">
    <div class="container-fluid">
    </div>
        <ul class="nav nav-pills ml-4 mb-3 mt-5 justify-content-start" id="pills-tab" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" id="pills-dashboard-tab" data-toggle="pill" href="#pills-dashboard"
                    role="tab" aria-controls="pills-dashboard" aria-selected="true"><i class="far fa-chart-bar"></i>
                    Dashboard</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="pills-orders-tab" data-toggle="pill" href="#pills-orders" role="tab"
                    aria-controls="pills-orders" aria-selected="false"><i class="fas fa-shopping-cart"></i>
                    Orders</a>
            </li>
            <!-- <li class="nav-item">
                <a class="nav-link" id="pills-series-tab" data-toggle="pill" href="#pills-series" role="tab"
                    aria-controls="pills-series" aria-selected="false"><i class="fas fa-file-invoice"></i> Reports</a>
            </li> -->
        </ul>
        <hr class="my-5 bg-dark">
        <!-------- Dashboard Page -------->
        <div class="tab-content" id="pills-tabContent">
            <div class="tab-pane fade show active" id="pills-dashboard" role="tabpanel"
                aria-labelledby="pills-dashboard-tab">
                <div class="col-md-12 border border-dark p-5 mt-5">
                    <div class="row">
                        <div class="col-md-4 text-center">
                            <h2 class="dashboard_heading_1">Revenue</h2>
                            <h2 class="primary-color mt-5">{{ revenue.price__sum }} <small>KWD</small></h2>
                        </div>
                        <div class="col-md-4 text-center">
                            <h2 class="dashboard_heading_1">Orders Made</h2>
                            <h2 class="primary-color mt-5">{{ total_orders }}</h2>
                        </div>
                        <div class="col-md-4 text-center">
                            <h2 class="dashboard_heading_1">Visitors</h2>
                            <h2 class="primary-color mt-5">1</h2>
                        </div>
                    </div>
                </div>
                <!-------- Top Videos Stats -------->
                <div class="col-md-12 border border-dark p-5 mt-5">
                    <h2 class="dashboard_heading_1">Top Videos</h2>
                    <table class="table stats mt-5">
                        <thead>
                            <tr class="d-flex">
                                <th class="col-3">Name</th>
                                <th class="col-3">Category</th>
                                <th class="col-9">Revenue</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for count in counts %}
                            <tr class="d-flex">
                                <td class="col-3">
                                    {{ count.project_title}}
                                </td>
                                <td class="col-3">
                                    {{ count.project_category }}
                                </td>
                                <td class="col-6">
                                    <div class="progress">
                                        <div class="progress-bar" role="progressbar" aria-valuenow="70"
                                            aria-valuemin="0" aria-valuemax="100"
                                            style="width:{{count.project_id__count|mul:10}}%">
                                            <span class="progress-caption"> {{ count.project_id__count }} </span>
                                        </div>
                                        <span class="progress-revenue mt-1 ml-4">
                                            <span class="primary-color">
                                                {{ count.price | mul:count.project_id__count }} KWD
                                            </span>
                                        </span>
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <!-------- Top Category Stats -------->
                <div class="col-md-12 border border-dark p-5 mt-5">
                    <h2 class="dashboard_heading_1">Top Category</h2>
                    <table class="table stats mt-5">
                        <thead>
                            <tr class="d-flex">
                                <th class="col-3">Category Name</th>
                                <th class="col-9">Revenue</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr class="d-flex">
                                <td class="col-3">
                                    Theatre
                                </td>
                                <td class="col-9">
                                    <div class="progress">
                                        <div class="progress-bar" role="progressbar" aria-valuenow="70"
                                            aria-valuemin="0" aria-valuemax="100"
                                            style="width:{{ theatre_orders|mul:10 }}%">
                                            <span class="progress-caption">{{ theatre_orders }}</span>
                                        </div>
                                        <span class="progress-revenue mt-1 ml-4">
                                            <span class="primary-color">
                                                {{ theatre_revenue.price__sum }} KWD
                                            </span>
                                        </span>
                                    </div>
                                </td>
                            </tr>
                            <tr class="d-flex">
                                <td class="col-3">
                                    Movie
                                </td>
                                <td class="col-9">
                                    <div class="progress">
                                        <div class="progress-bar" role="progressbar" aria-valuenow="70"
                                            aria-valuemin="0" aria-valuemax="100"
                                            style="width:{{ movie_orders|mul:10 }}%">
                                            <span class="progress-caption"> {{ movie_orders }} </span>
                                        </div>
                                        <span class="progress-revenue mt-1 ml-4">
                                            <span class="primary-color">
                                                {{ movie_revenue.price__sum }} KWD
                                            </span>
                                        </span>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                 <!-------- Daily Revenue Stats -------->
                <div class="col-md-12 border border-dark p-5 mt-5">
                    <h2 class="dashboard_heading_1">Daily Revenue</h2>
                    <table class="table stats mt-5">
                        <thead>
                            <tr class="d-flex">
                                <th class="col-3">Date</th>
                                <th class="col-9">Revenue</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for date in dates %}
                            <tr class="d-flex">
                                <td class="col-3">
                                    {{ date.order_date__date}}
                                </td>
                                <td class="col-9">
                                    <div class="progress">
                                        <div class="progress-bar" role="progressbar" aria-valuenow="70"
                                            aria-valuemin="0" aria-valuemax="100"
                                            style="width:{{ date.sum }}%">
                                            <span class="progress-caption"> {{ date.project_id__count }} </span>
                                        </div>
                                        <span class="progress-revenue mt-1 ml-4">
                                            <span class="primary-color">
                                                {{ date.sum }} KWD
                                            </span>
                                        </span>
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <!-------- Orders Page -------->
            <div class="tab-pane fade show" id="pills-orders" role="tabpanel" aria-labelledby="pills-orders-tab">
                {% if orders %}
                <table id="orders" class="table table-dark text-center mt-4">
                    <thead>
                        <tr>
                            <th scope="col">Id</th>
                            <th scope="col">User name</th>
                            <th scope="col">Email Id</th>
                            <th scope="col">Order Item</th>
                            <th scope="col">Order Category</th>
                            <th scope="col">Order Date & Time</th>
                            <th scope="col">Order Price</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for order in orders %}
                        <tr>
                            <td>{{ order.id }}</td>
                            <td>{{ order.name }}</td>
                            <td>{{ order.email }}</td>
                            <td>{{ order.project_title }}</td>
                            <td>{{ order.project_category }}</td>
                            <td>{{ order.order_date | date }}</td>
                            <td>{{ order.price }} <small>KWD</small></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% else %}
                <div class="container p-5 text-center mt-5" style="border: 1.5px solid #4ecca3;">
                    <h2 class="heading-secondary primary-color">No Orders made yet.</h2>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</section>
{% include 'partials/_footer.html' %}
{% endblock%}

pages/templates/accounts/dashboard.html
{% extends 'layout.html' %}
{% block content %}
{% load static %}
{% include 'partials/_navbar.html' %}
<link rel="stylesheet" href="{% static 'app/css/input.css'%}">
<section class="section-dashboard">
    <div class="container">
        {% include 'partials/_alerts.html' %}
        <h2 class="heading-primary">
            Your Profile
        </h2>
        <div class="row mt-5">
            <div class="col-md-5 stat_box">
                <p class="heading-tertiary text-muted">
                    Profile Details
                </p>
                <h2 class="heading-secondary mt-3">
                    {{ user.first_name }} <span class="primary-color">{{ user.last_name }}</span>
                </h2>
                <span class="text-muted place"><i class="far fa-envelope"></i> {{ user.email }}</span>
                <span class="text-muted place mt-1">Member since <span
                        class="primary-color">{{ user.date_joined | date }}</span></span>
                <div class="form-row mt-4">
                    <a href="" class="button-primary-small" data-toggle="modal" data-target="#exampleModal"><i
                            class="far fa-edit"></i> Edit Profile</a>
                    <a href="{% url 'password_change' %}" class="button-white-small ml-3"><i class="fas fa-lock"></i>
                        Change
                        Password</a>
                    <!--- Edit Profile Modal -->
                    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog"
                        aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-body">
                                    <h4 class="modal-title">
                                        Edit
                                        <span class="primary-color">
                                            Profile
                                        </span>
                                    </h4>
                                    <div class="edit-form mt-4">
                                        <form method="post">
                                            {% csrf_token %}
                                            {{ u_form }}
                                            <div class="form-group mt-4">
                                                <button class="button-primary btn-block" type="submit">Update
                                                    Profile</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                     <!--- End of Edit Profile Modal -->
                </div>
            </div>
            <div class="col-md-3 stat_box text-center">
                <h2 class="heading-tertiary text-muted">
                    Videos purchased
                </h2>
                <p class="stat_box__icon">
                    <i class="fas fa-video mr-5 text-muted"></i>
                    <span class="primary-color">
                        {{ videos_count }}
                    </span>
                </p>
            </div>
            <div class="col-md-3 stat_box text-center">
                <h2 class="heading-tertiary text-muted">
                    Total Money spent
                </h2>
                <p class="stat_box__content">
                    <span class="text-muted">KWD</span>
                    <span class="primary-color">
                        {{ money_spent.price__sum }}
                    </span>
                </p>
            </div>
        </div>
        {% if orders %}
        <hr class="bg-dark my-5">
        <h2 class="heading-secondary">
            Your Videos
        </h2>
        <div class="row mt-5">
            {% for order in orders %}
                <div class="col-lg-3 col-md-4 col-sm-6">
                    <a href="{% url 'projects:project_detail' order.project_slug %}">
                        <div class="card">
                            <div class="card-img-top">
                                <img src="{{ order.photo_card }}" class="img-fluid">
                            </div>
                            <div class="card-body text-center">
                                <h2 class="card-title">{{ order.project_title }}</h2>
                                <p class="card-text text-muted">
                                    <span>{{ order.order_date | timesince }} ago</span>
                                </p>
                            </div>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
        {% else %}
        <div class="container no_video_found p-5 text-center">
            <img src="{% static 'app/images/logo/no_video_found.svg'%}">
            <p class="heading-tertiary primary-color">You don't have any videos yet.</p>
        </div>
        {% endif %}
        <hr class="bg-dark my-5">
        <div class="form-row">
            <a href="{% url 'projects:projects' %}" class="button-white-small"><i class="fas fa-video"></i> Explore Videos</a>
            {% if request.user.is_superuser %}
            <a href="{% url 'admin_dashboard' %}" class="button-special-small ml-3"><i class="fas fa-tachometer-alt"></i> Admin
                Dashboard</a>
            {% endif %}
        </div>
    </div>
</section>
{% include 'partials/_footer.html' %}
{% endblock%}

pages/templates/accounts/login.html
{% extends 'layout.html' %}
{% block content %}
{% load humanize %}
{% load static %}
{% include 'partials/_navbar.html' %}
<link rel="stylesheet" href="{% static 'app/css/input.css'%}">
<section class="section-accounts">
    <div class="container">
        <div class="col-lg-6 col-md-12 col-sm-12 offset-lg-3 auth-container">
            <h1 class="heading-primary text-center">Login</h1>
            <span class="text-muted place text-center">
                Enter your username and password to login
            </span>
            <hr class="bg-dark mt-3">
            {% include 'partials/_alerts.html' %}
            <form action="{% url 'login' %}" method="POST">
                {% csrf_token %}
                <div class="form-group mt-5">
                    <label for="username">Username</label>
                    <input name="username" placeholder="Please enter your username" required autocomplete="off">
                </div>
                <div class="form-group mt-5">
                    <label for="password">Password</label>
                    <input name="password" type="password" placeholder="Please enter your password" required
                        autocomplete="off">
                </div>
                <div class="form-group mt-5">
                    <button class="button-primary btn-block" type="submit">Login</button>
                </div>
                <div class="form-group mt-5 text-center">
                    <a href="{% url 'register' %}" class="auth-link">Don't have an account ? Register here</a>
                </div>
                <div class="form-group mt-5 text-center">
                    <a href="{% url 'password_reset' %}" class="auth-link">Forgot Password ?</a>
                </div>
            </form>
        </div>
    </div>
</section>
{% include 'partials/_footer.html' %}
{% endblock%}

pages/templates/accounts/logout.html
{% extends 'layout.html' %}
{% block content %}
{% load static %}
{% include 'partials/_navbar.html' %}
<section class="section-logout">
    <div class="container">
        <div class="container logout-container text-center" style="margin-top: 10rem;">
            <img src="{% static 'app/images/logo/bye.svg' %}" class="handshake">
            <p class="heading-tertiary primary-color mt-5">Thank you for visitng us. You are now logged out.</p>
            <div class="form-group mt-5">
                <a href="{% url 'login' %}" class="button-primary">
                    <i class="fas fa-sign-in-alt"></i> Login again
                </a>
            </div>
            <p class="place mt-4 text-muted">OR</p>
            <div class="form-group mt-4">
                <a href="/" class="auth-link">
                    <i class="fas fa-arrow-left"></i> Back to HomePage
                </a>
            </div>
        </div>
    </div>
</section>
{% include 'partials/_footer.html' %}
{% endblock %}

pages/templates/accounts/password_change_done.html
{% extends 'layout.html' %}
{% block content %}
{% load static %}
{% include 'partials/_navbar.html' %}
<section class="section-logout">
    <div class="container logout-container text-center" style="border: 1.5px solid #4ecca3; margin-top: 10rem;">
        <h2 class="heading-primary primary-color"><i class="far fa-check-circle mr-2" style="font-size: 3rem;"></i>
            Your password has been changed successfully
        </h2>
    </div>
</section>
{% include 'partials/_footer.html' %}
{% endblock %}

pages/templates/accounts/password_reset.html
{% extends 'layout.html' %}
{% block content %}
{% load humanize %}
{% load static %}
{% include 'partials/_navbar.html' %}
<link rel="stylesheet" href="{% static 'app/css/input.css'%}">
<section class="section-accounts">
    <div class="container">
        <div class="col-lg-8 col-md-12 col-sm-12 offset-lg-2 auth-container">
            <h3 class="heading-primary text-center">Forget Password</h3>
            <span class="text-muted place text-center">
                Enter your email id, we will send you a link to reset your password
            </span>
            <hr class="bg-dark mt-3">
            {% include 'partials/_alerts.html' %}
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="form-group mt-5 text-center">
                    <button class="button-primary btn-block" type="submit">Send Reset Link</button>
                </div>
            </form> 
        </div>
    </div>
</section>
{% include 'partials/_footer.html' %}
{% endblock %}